/**
 * Cotización → pedido bridge for the "fruver" vertical.
 *
 * These helpers connect a persisted Quote to the existing order engine
 * (`create-order`) and the quotes admin endpoint (`quotes-admin`
 * `mark-converted`). The logic lives here — free of DOM and framework glue —
 * so the item-description builder and the idempotency guard can be
 * unit- and property-tested (Properties 4 and 5).
 *
 * Reuse-first: no new backend endpoint is introduced. The network operations
 * (creating the order and marking the quote converted) are injected as
 * dependencies so this module stays pure and testable; the panel wires the
 * real HTTP calls (task 8.2).
 */

import type { QuoteLine } from "./types";

/**
 * Builds a human-readable item description from quote lines (R7.1).
 *
 * Produces a comma-separated list where every line contributes its quantity,
 * unit and name, e.g. `"2 kg Tomate, 3 unidad Aguacate"`. Every input line is
 * represented exactly once and in order, so the resulting text is complete and
 * suitable for the existing ticket and WhatsApp templates (which consume
 * `items_text`).
 *
 * @param lines - The quote lines to describe.
 * @returns The joined description; an empty string when there are no lines.
 */
export function linesToItemsText(lines: QuoteLine[]): string {
  return lines
    .map((line) => `${line.qty} ${line.unit} ${line.name}`)
    .join(", ");
}

/**
 * Minimal Quote shape required to convert a quote into an order.
 *
 * Mirrors the relevant fields of {@link import("./types").Quote}; kept narrow
 * so callers (and tests) can pass just what the bridge needs.
 */
export interface ConvertibleQuote {
  id: string;
  lines: QuoteLine[];
  estimated_total: number;
  /** Link to a previously created order; when set, conversion is a no-op (R7.3). */
  order_id: string | null;
}

/** Input for {@link convertQuoteToOrder}. */
export interface ConvertQuoteInput {
  /** The quote to convert (includes `lines`, `estimated_total`, `order_id`). */
  quote: ConvertibleQuote;
  businessId: string;
  businessSlug: string;
  customerName: string;
  /** Mandatory: required by the ticket/WhatsApp flow (R7.5). */
  customerPhone: string;
  customerAddress?: string;
}

/**
 * Payload sent to the existing `create-order` endpoint. Field names match the
 * `create-order` contract (`customerName`, `customerPhone`, `itemsText`,
 * `total`, ...).
 */
export interface CreateOrderPayload {
  businessSlug: string;
  customerName: string;
  customerPhone: string;
  itemsText: string;
  total: number;
  customerAddress?: string;
}

/** Result returned by the injected create-order operation. */
export interface CreateOrderResult {
  /** The generated order number, used to build the public ticket URL. */
  orderNumber: string;
  /** The ticket token generated by `create-order` (R7.2). */
  ticketToken: string;
}

/**
 * Dependencies injected into {@link convertQuoteToOrder}. Keeping the network
 * operations as parameters lets the panel supply real HTTP calls while tests
 * (Property 5) supply spies/mocks and assert the idempotency guard.
 */
export interface ConvertQuoteDeps {
  /** Creates the order via `create-order`; returns its number and token. */
  createOrder: (payload: CreateOrderPayload) => Promise<CreateOrderResult>;
  /** Links `order_id` and marks the quote `convertida` via `quotes-admin`. */
  markConverted: (args: {
    businessId: string;
    quoteId: string;
    orderId: string;
  }) => Promise<void>;
}

/** Result of {@link convertQuoteToOrder}. */
export interface ConvertQuoteResult {
  /** The order number backing the ticket. */
  orderNumber: string;
  /** Public ticket URL for delivery tracking (`/tiquete?...`). */
  ticketUrl: string;
  /** Whether an order was actually created on this call (`false` when idempotent). */
  created: boolean;
}

/**
 * Builds the public ticket URL for an order (delivery tracking + QR, R7.2).
 */
export function buildTicketUrl(orderNumber: string, businessSlug: string): string {
  const number = encodeURIComponent(orderNumber);
  const slug = encodeURIComponent(businessSlug);
  return `/tiquete?number=${number}&slug=${slug}`;
}

/**
 * Converts a quote into an order with a public ticket, then marks the quote
 * converted (R7.1, R7.3).
 *
 * Idempotency (Property 5, R7.3): if the quote already has an `order_id`, this
 * function does **not** call `createOrder` — it returns the existing order's
 * ticket info with `created: false`, guaranteeing a single order per quote.
 * Otherwise it validates the mandatory phone (R7.5), calls `createOrder` with
 * an `itemsText` derived from the lines and the estimated total, then links the
 * resulting `order_id` back to the quote via `markConverted`.
 *
 * @param input - Quote, business and customer data.
 * @param deps - Injected create-order and mark-converted operations.
 * @returns The order number, public ticket URL, and whether an order was created.
 * @throws When the customer phone is missing/blank (R7.5).
 */
export async function convertQuoteToOrder(
  input: ConvertQuoteInput,
  deps: ConvertQuoteDeps,
): Promise<ConvertQuoteResult> {
  const { quote, businessId, businessSlug, customerName, customerPhone } = input;

  // Idempotency guard: never create a second order for the same quote (R7.3).
  if (quote.order_id != null && quote.order_id !== "") {
    return {
      orderNumber: quote.order_id,
      ticketUrl: buildTicketUrl(quote.order_id, businessSlug),
      created: false,
    };
  }

  // Phone is mandatory for the ticket/WhatsApp flow (R7.5).
  if (typeof customerPhone !== "string" || customerPhone.trim() === "") {
    throw new Error("El teléfono del cliente es obligatorio para crear el pedido.");
  }

  const result = await deps.createOrder({
    businessSlug,
    customerName,
    customerPhone,
    itemsText: linesToItemsText(quote.lines),
    total: quote.estimated_total,
    customerAddress: input.customerAddress,
  });

  await deps.markConverted({
    businessId,
    quoteId: quote.id,
    orderId: result.orderNumber,
  });

  return {
    orderNumber: result.orderNumber,
    ticketUrl: buildTicketUrl(result.orderNumber, businessSlug),
    created: true,
  };
}
